services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    hostname: bot
    env_file:
      - .env
    volumes:
      - schemaVol:/svc/schema/
    networks:
      - appNetwork

networks:
  appNetwork:

volumes:
  schemaVol:
