echo This batch file starts the https server properly

echo Generating new private key...
openssl genrsa -out certs/key.pem 2048

echo Generating a certificate signing request...
openssl req -new -key certs/key.pem -out certs/csr.pem -batch

echo Generating self-signed certificate...
openssl x509 -req -days 365 -in certs/csr.pem -signkey certs/key.pem -out certs/cert.pem

echo Installing requirements....
pip install -r requirements.txt

echo Starting file server...
python -m bot
